- hosts: localhost
  become: true

  tasks:
    
    - name: installing packages
      yum:  
        name: ["yum-utils","device-mapper-persistent-data","lvm2"] 
        state: "installed"

    - name: add  repository
      shell: |
             yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
             yum clean all

    - name: installing packages
      yum:  
        name: ["docker-ce","docker-ce-cli","containerd.io"]
        state: "installed"

    - name: start the service
      service:
        name: "docker"
        state: "restarted"

    
     
     
     

  
